# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6bf92a523d729dd366e229f93a76e4ffad05676985cfb68ee227c453eb24272ce1c5719ad650e25f470ebc9a6b10f47467710b40fa35fc264d3826c1816a431

test:
  secret_key_base: cb7bc963c79ab89d7199f3c02c27878dea756e55688c1da1a02232c650eea852e8c20bf351e80c814652cac9a338dab3935572c1191cb49ec0ea232fc7b870f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
